[build]
command = "npm run build"

[context.production]
environment = { NODE_VERSION = "18.9.0" }

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

[[edge_functions]]
path = "/hub/*"
function = "proxy-requests-wildcard"

[[edge_functions]]
path = "/hub"
function = "proxy-requests-wildcard"

[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "strict-origin-when-cross-origin"
